Drop support for Python < 3.6
Issue #86.

[Exported from e089383804e1aa58a34f89bffaf76a555f52094f]

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,59 +1,77 @@
-# bazel boiler plate mostly taken from rules_go/.travis.yml. See:
-#   https://github.com/bazelbuild/rules_go/blob/master/.travis.yml
-
-# trusty beta image has jdk8, gcc4.8.4
-# FIXME(linux): dist: trusty
+# build environment
+#
+# We need the extra RAM that a non-container build gives us.
+#
+# See: https://docs.travis-ci.com/user/ci-environment/
 sudo: required
-# xcode8 has jdk8
-osx_image: xcode8
-# Not technically required but suppresses 'Ruby' in Job status message.
-language: java
+dist: trusty
 
-# workaround submodule public key access.
-# See: http://stackoverflow.com/a/24600210
-git:
-  submodules: false
+language: python
 
-os:
-  # FIXME(linux): - linux
-  - osx
+python:
+  - "3.6"
+  - "3.7-dev"
 
-# FIXME(linux):
-# addons:
-#   apt:
-#     sources:
-#       - ubuntu-toolchain-r-test
-#     packages:
-#       - clang-3.6
+cache:
+  directories:
+    - .cache
+    - native/cmake
+    - native/gpuverify
+    - native/libclc
+    - native/llvm
+    - native/ninja
+    - native/oclgrind
+
+addons:
+  apt:
+    sources:
+      - llvm-toolchain-precise-3.7
+      - ubuntu-toolchain-r-test
+    packages:
+      - gcc-5
+      - g++-5
+      - clang-3.6
+      - libhdf5-serial-dev
+      - python-dev
+      - mono-complete
+
+env:
+  global:
+    - CC=clang
+    - CXX=clang++
 
 before_install:
-  - cat .gitmodules
-  - sed -i 's,git@github.com:,https://github.com/,' .gitmodules
-  - cat .gitmodules
-  - git submodule update --init --recursive
-  - |
-    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
-      brew update
-      brew install bazel
-    else
-      echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
-      curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
-      sudo apt-get update
-      dpkg -s 'bazel' &>/dev/null || sudo apt-get install -y bazel
-    fi
-
-script:
-  - source .env
+  - pip install --upgrade pip
+  - pip --version   # updated pip
+  - pip install coveralls
+  - sudo apt-get update -qq
+  - ldd --version   # glibc version
   - $CC --version   # c compiler
   - $CXX --version  # c++ compiler
-  - |
-    bazel \
-      test \
-        --verbose_failures \
-        --sandbox_debug \
-        --test_output=errors \
-        --test_strategy=standalone \
-        --spawn_strategy=standalone \
-        --genrule_strategy=standalone \
-        --local_resources=400,1,1.0 \
-        //learn/ctci:all
+
+# A clean Travis CI build will timeout after 50 minutes and fail. Irritatingly,
+# this means that the caches are not updated, so we can't incrementally build
+# the project by restarting the job. The workaround is to kill the build after
+# a time limit and then restart the job by hand:
+#
+# install:  # cache cold (runs build in 30min chunks, restart job until complete)
+#   - ./configure -b
+#   - timeout 1800 make all || true
+#   - touch NORUN
+#
+install:  # cache hot
+  - ./configure -b
+  - make all
+  - make install
+  - pip freeze  # python package versions
+
+script:
+  - test -f NORUN || coverage run --source=clgen ./setup.py test
+
+after_success:
+  - test -f NORUN || coveralls
+
+notifications:
+  email:
+    on_success: always # [always|never|change]
+    on_failure: always # [always|never|change]
